[2023-02-26 13:11:41,273] {processor.py:153} INFO - Started process (PID=1773) to work on /opt/airflow/dags/analytics_appopen_v2.py
[2023-02-26 13:11:41,274] {processor.py:641} INFO - Processing file /opt/airflow/dags/analytics_appopen_v2.py for tasks to queue
[2023-02-26 13:11:41,275] {logging_mixin.py:115} INFO - [2023-02-26 13:11:41,275] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/analytics_appopen_v2.py
[2023-02-26 13:11:41,338] {logging_mixin.py:115} INFO - [2023-02-26 13:11:41,335] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/analytics_appopen_v2.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/analytics_appopen_v2.py", line 9, in <module>
    from default_args import default_args
ModuleNotFoundError: No module named 'default_args'
[2023-02-26 13:11:41,340] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/analytics_appopen_v2.py
[2023-02-26 13:11:41,360] {processor.py:161} INFO - Processing /opt/airflow/dags/analytics_appopen_v2.py took 0.090 seconds
[2023-02-26 13:12:11,521] {processor.py:153} INFO - Started process (PID=1802) to work on /opt/airflow/dags/analytics_appopen_v2.py
[2023-02-26 13:12:11,522] {processor.py:641} INFO - Processing file /opt/airflow/dags/analytics_appopen_v2.py for tasks to queue
[2023-02-26 13:12:11,523] {logging_mixin.py:115} INFO - [2023-02-26 13:12:11,522] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/analytics_appopen_v2.py
[2023-02-26 13:12:11,543] {logging_mixin.py:115} INFO - [2023-02-26 13:12:11,540] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/analytics_appopen_v2.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/analytics_appopen_v2.py", line 9, in <module>
    from default_args import default_args
ModuleNotFoundError: No module named 'default_args'
[2023-02-26 13:12:11,543] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/analytics_appopen_v2.py
[2023-02-26 13:12:11,561] {processor.py:161} INFO - Processing /opt/airflow/dags/analytics_appopen_v2.py took 0.043 seconds
[2023-02-26 13:12:41,755] {processor.py:153} INFO - Started process (PID=1822) to work on /opt/airflow/dags/analytics_appopen_v2.py
[2023-02-26 13:12:41,755] {processor.py:641} INFO - Processing file /opt/airflow/dags/analytics_appopen_v2.py for tasks to queue
[2023-02-26 13:12:41,756] {logging_mixin.py:115} INFO - [2023-02-26 13:12:41,756] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/analytics_appopen_v2.py
[2023-02-26 13:12:41,771] {logging_mixin.py:115} INFO - [2023-02-26 13:12:41,770] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/analytics_appopen_v2.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/analytics_appopen_v2.py", line 9, in <module>
    from default_args import default_args
ModuleNotFoundError: No module named 'default_args'
[2023-02-26 13:12:41,772] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/analytics_appopen_v2.py
[2023-02-26 13:12:41,786] {processor.py:161} INFO - Processing /opt/airflow/dags/analytics_appopen_v2.py took 0.034 seconds
[2023-02-26 13:13:11,978] {processor.py:153} INFO - Started process (PID=1852) to work on /opt/airflow/dags/analytics_appopen_v2.py
[2023-02-26 13:13:11,978] {processor.py:641} INFO - Processing file /opt/airflow/dags/analytics_appopen_v2.py for tasks to queue
[2023-02-26 13:13:11,979] {logging_mixin.py:115} INFO - [2023-02-26 13:13:11,979] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/analytics_appopen_v2.py
[2023-02-26 13:13:11,996] {logging_mixin.py:115} INFO - [2023-02-26 13:13:11,994] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/analytics_appopen_v2.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/analytics_appopen_v2.py", line 9, in <module>
    from default_args import default_args
ModuleNotFoundError: No module named 'default_args'
[2023-02-26 13:13:11,996] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/analytics_appopen_v2.py
[2023-02-26 13:13:12,060] {processor.py:161} INFO - Processing /opt/airflow/dags/analytics_appopen_v2.py took 0.085 seconds
[2023-02-26 13:13:42,255] {processor.py:153} INFO - Started process (PID=1882) to work on /opt/airflow/dags/analytics_appopen_v2.py
[2023-02-26 13:13:42,256] {processor.py:641} INFO - Processing file /opt/airflow/dags/analytics_appopen_v2.py for tasks to queue
[2023-02-26 13:13:42,257] {logging_mixin.py:115} INFO - [2023-02-26 13:13:42,257] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/analytics_appopen_v2.py
[2023-02-26 13:13:42,280] {logging_mixin.py:115} INFO - [2023-02-26 13:13:42,277] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/analytics_appopen_v2.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/analytics_appopen_v2.py", line 9, in <module>
    from default_args import default_args
ModuleNotFoundError: No module named 'default_args'
[2023-02-26 13:13:42,281] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/analytics_appopen_v2.py
[2023-02-26 13:13:42,302] {processor.py:161} INFO - Processing /opt/airflow/dags/analytics_appopen_v2.py took 0.050 seconds
[2023-02-26 13:14:12,472] {processor.py:153} INFO - Started process (PID=1904) to work on /opt/airflow/dags/analytics_appopen_v2.py
[2023-02-26 13:14:12,473] {processor.py:641} INFO - Processing file /opt/airflow/dags/analytics_appopen_v2.py for tasks to queue
[2023-02-26 13:14:12,474] {logging_mixin.py:115} INFO - [2023-02-26 13:14:12,474] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/analytics_appopen_v2.py
[2023-02-26 13:14:12,494] {logging_mixin.py:115} INFO - [2023-02-26 13:14:12,492] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/analytics_appopen_v2.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/analytics_appopen_v2.py", line 9, in <module>
    from default_args import default_args
ModuleNotFoundError: No module named 'default_args'
[2023-02-26 13:14:12,495] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/analytics_appopen_v2.py
[2023-02-26 13:14:12,512] {processor.py:161} INFO - Processing /opt/airflow/dags/analytics_appopen_v2.py took 0.043 seconds
[2023-02-26 13:14:42,700] {processor.py:153} INFO - Started process (PID=1934) to work on /opt/airflow/dags/analytics_appopen_v2.py
[2023-02-26 13:14:42,701] {processor.py:641} INFO - Processing file /opt/airflow/dags/analytics_appopen_v2.py for tasks to queue
[2023-02-26 13:14:42,701] {logging_mixin.py:115} INFO - [2023-02-26 13:14:42,701] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/analytics_appopen_v2.py
[2023-02-26 13:14:42,720] {logging_mixin.py:115} INFO - [2023-02-26 13:14:42,718] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/analytics_appopen_v2.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/analytics_appopen_v2.py", line 9, in <module>
    from default_args import default_args
ModuleNotFoundError: No module named 'default_args'
[2023-02-26 13:14:42,720] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/analytics_appopen_v2.py
[2023-02-26 13:14:42,734] {processor.py:161} INFO - Processing /opt/airflow/dags/analytics_appopen_v2.py took 0.037 seconds
[2023-02-26 13:15:12,919] {processor.py:153} INFO - Started process (PID=1965) to work on /opt/airflow/dags/analytics_appopen_v2.py
[2023-02-26 13:15:12,920] {processor.py:641} INFO - Processing file /opt/airflow/dags/analytics_appopen_v2.py for tasks to queue
[2023-02-26 13:15:12,920] {logging_mixin.py:115} INFO - [2023-02-26 13:15:12,920] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/analytics_appopen_v2.py
[2023-02-26 13:15:12,939] {logging_mixin.py:115} INFO - [2023-02-26 13:15:12,937] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/analytics_appopen_v2.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/analytics_appopen_v2.py", line 9, in <module>
    from default_args import default_args
ModuleNotFoundError: No module named 'default_args'
[2023-02-26 13:15:12,940] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/analytics_appopen_v2.py
[2023-02-26 13:15:12,953] {processor.py:161} INFO - Processing /opt/airflow/dags/analytics_appopen_v2.py took 0.036 seconds
[2023-02-26 13:15:43,141] {processor.py:153} INFO - Started process (PID=1995) to work on /opt/airflow/dags/analytics_appopen_v2.py
[2023-02-26 13:15:43,142] {processor.py:641} INFO - Processing file /opt/airflow/dags/analytics_appopen_v2.py for tasks to queue
[2023-02-26 13:15:43,142] {logging_mixin.py:115} INFO - [2023-02-26 13:15:43,142] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/analytics_appopen_v2.py
[2023-02-26 13:15:43,159] {logging_mixin.py:115} INFO - [2023-02-26 13:15:43,157] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/analytics_appopen_v2.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/analytics_appopen_v2.py", line 9, in <module>
    from default_args import default_args
ModuleNotFoundError: No module named 'default_args'
[2023-02-26 13:15:43,160] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/analytics_appopen_v2.py
[2023-02-26 13:15:43,175] {processor.py:161} INFO - Processing /opt/airflow/dags/analytics_appopen_v2.py took 0.036 seconds
[2023-02-26 13:16:13,344] {processor.py:153} INFO - Started process (PID=2016) to work on /opt/airflow/dags/analytics_appopen_v2.py
[2023-02-26 13:16:13,344] {processor.py:641} INFO - Processing file /opt/airflow/dags/analytics_appopen_v2.py for tasks to queue
[2023-02-26 13:16:13,345] {logging_mixin.py:115} INFO - [2023-02-26 13:16:13,345] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/analytics_appopen_v2.py
[2023-02-26 13:16:13,361] {logging_mixin.py:115} INFO - [2023-02-26 13:16:13,359] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/analytics_appopen_v2.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/analytics_appopen_v2.py", line 9, in <module>
    from default_args import default_args
ModuleNotFoundError: No module named 'default_args'
[2023-02-26 13:16:13,362] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/analytics_appopen_v2.py
[2023-02-26 13:16:13,376] {processor.py:161} INFO - Processing /opt/airflow/dags/analytics_appopen_v2.py took 0.035 seconds
[2023-02-26 13:16:43,587] {processor.py:153} INFO - Started process (PID=2046) to work on /opt/airflow/dags/analytics_appopen_v2.py
[2023-02-26 13:16:43,588] {processor.py:641} INFO - Processing file /opt/airflow/dags/analytics_appopen_v2.py for tasks to queue
[2023-02-26 13:16:43,588] {logging_mixin.py:115} INFO - [2023-02-26 13:16:43,588] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/analytics_appopen_v2.py
[2023-02-26 13:16:43,606] {logging_mixin.py:115} INFO - [2023-02-26 13:16:43,604] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/analytics_appopen_v2.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/analytics_appopen_v2.py", line 9, in <module>
    from default_args import default_args
ModuleNotFoundError: No module named 'default_args'
[2023-02-26 13:16:43,607] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/analytics_appopen_v2.py
[2023-02-26 13:16:43,621] {processor.py:161} INFO - Processing /opt/airflow/dags/analytics_appopen_v2.py took 0.037 seconds
[2023-02-26 13:17:13,800] {processor.py:153} INFO - Started process (PID=2076) to work on /opt/airflow/dags/analytics_appopen_v2.py
[2023-02-26 13:17:13,801] {processor.py:641} INFO - Processing file /opt/airflow/dags/analytics_appopen_v2.py for tasks to queue
[2023-02-26 13:17:13,801] {logging_mixin.py:115} INFO - [2023-02-26 13:17:13,801] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/analytics_appopen_v2.py
[2023-02-26 13:17:13,818] {logging_mixin.py:115} INFO - [2023-02-26 13:17:13,816] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/analytics_appopen_v2.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/analytics_appopen_v2.py", line 9, in <module>
    from default_args import default_args
ModuleNotFoundError: No module named 'default_args'
[2023-02-26 13:17:13,819] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/analytics_appopen_v2.py
[2023-02-26 13:17:13,832] {processor.py:161} INFO - Processing /opt/airflow/dags/analytics_appopen_v2.py took 0.034 seconds
[2023-02-26 13:17:44,011] {processor.py:153} INFO - Started process (PID=2106) to work on /opt/airflow/dags/analytics_appopen_v2.py
[2023-02-26 13:17:44,012] {processor.py:641} INFO - Processing file /opt/airflow/dags/analytics_appopen_v2.py for tasks to queue
[2023-02-26 13:17:44,013] {logging_mixin.py:115} INFO - [2023-02-26 13:17:44,013] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/analytics_appopen_v2.py
[2023-02-26 13:17:44,030] {logging_mixin.py:115} INFO - [2023-02-26 13:17:44,028] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/analytics_appopen_v2.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/analytics_appopen_v2.py", line 9, in <module>
    from default_args import default_args
ModuleNotFoundError: No module named 'default_args'
[2023-02-26 13:17:44,031] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/analytics_appopen_v2.py
[2023-02-26 13:17:44,045] {processor.py:161} INFO - Processing /opt/airflow/dags/analytics_appopen_v2.py took 0.036 seconds
[2023-02-26 13:18:14,210] {processor.py:153} INFO - Started process (PID=2127) to work on /opt/airflow/dags/analytics_appopen_v2.py
[2023-02-26 13:18:14,211] {processor.py:641} INFO - Processing file /opt/airflow/dags/analytics_appopen_v2.py for tasks to queue
[2023-02-26 13:18:14,211] {logging_mixin.py:115} INFO - [2023-02-26 13:18:14,211] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/analytics_appopen_v2.py
[2023-02-26 13:18:14,229] {logging_mixin.py:115} INFO - [2023-02-26 13:18:14,227] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/analytics_appopen_v2.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/analytics_appopen_v2.py", line 9, in <module>
    from default_args import default_args
ModuleNotFoundError: No module named 'default_args'
[2023-02-26 13:18:14,230] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/analytics_appopen_v2.py
[2023-02-26 13:18:14,244] {processor.py:161} INFO - Processing /opt/airflow/dags/analytics_appopen_v2.py took 0.036 seconds
[2023-02-26 13:18:44,427] {processor.py:153} INFO - Started process (PID=2158) to work on /opt/airflow/dags/analytics_appopen_v2.py
[2023-02-26 13:18:44,428] {processor.py:641} INFO - Processing file /opt/airflow/dags/analytics_appopen_v2.py for tasks to queue
[2023-02-26 13:18:44,429] {logging_mixin.py:115} INFO - [2023-02-26 13:18:44,429] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/analytics_appopen_v2.py
[2023-02-26 13:18:44,447] {logging_mixin.py:115} INFO - [2023-02-26 13:18:44,444] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/analytics_appopen_v2.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/analytics_appopen_v2.py", line 9, in <module>
    from default_args import default_args
ModuleNotFoundError: No module named 'default_args'
[2023-02-26 13:18:44,448] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/analytics_appopen_v2.py
[2023-02-26 13:18:44,462] {processor.py:161} INFO - Processing /opt/airflow/dags/analytics_appopen_v2.py took 0.038 seconds
[2023-02-26 13:19:14,656] {processor.py:153} INFO - Started process (PID=2188) to work on /opt/airflow/dags/analytics_appopen_v2.py
[2023-02-26 13:19:14,658] {processor.py:641} INFO - Processing file /opt/airflow/dags/analytics_appopen_v2.py for tasks to queue
[2023-02-26 13:19:14,659] {logging_mixin.py:115} INFO - [2023-02-26 13:19:14,659] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/analytics_appopen_v2.py
[2023-02-26 13:19:14,682] {logging_mixin.py:115} INFO - [2023-02-26 13:19:14,680] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/analytics_appopen_v2.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/analytics_appopen_v2.py", line 9, in <module>
    from default_args import default_args
ModuleNotFoundError: No module named 'default_args'
[2023-02-26 13:19:14,683] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/analytics_appopen_v2.py
[2023-02-26 13:19:14,699] {processor.py:161} INFO - Processing /opt/airflow/dags/analytics_appopen_v2.py took 0.046 seconds
[2023-02-26 13:19:44,865] {processor.py:153} INFO - Started process (PID=2218) to work on /opt/airflow/dags/analytics_appopen_v2.py
[2023-02-26 13:19:44,866] {processor.py:641} INFO - Processing file /opt/airflow/dags/analytics_appopen_v2.py for tasks to queue
[2023-02-26 13:19:44,866] {logging_mixin.py:115} INFO - [2023-02-26 13:19:44,866] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/analytics_appopen_v2.py
[2023-02-26 13:19:44,886] {logging_mixin.py:115} INFO - [2023-02-26 13:19:44,883] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/analytics_appopen_v2.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/analytics_appopen_v2.py", line 9, in <module>
    from default_args import default_args
ModuleNotFoundError: No module named 'default_args'
[2023-02-26 13:19:44,887] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/analytics_appopen_v2.py
[2023-02-26 13:19:44,900] {processor.py:161} INFO - Processing /opt/airflow/dags/analytics_appopen_v2.py took 0.038 seconds
[2023-02-26 13:20:15,078] {processor.py:153} INFO - Started process (PID=2239) to work on /opt/airflow/dags/analytics_appopen_v2.py
[2023-02-26 13:20:15,078] {processor.py:641} INFO - Processing file /opt/airflow/dags/analytics_appopen_v2.py for tasks to queue
[2023-02-26 13:20:15,079] {logging_mixin.py:115} INFO - [2023-02-26 13:20:15,079] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/analytics_appopen_v2.py
[2023-02-26 13:20:15,096] {logging_mixin.py:115} INFO - [2023-02-26 13:20:15,094] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/analytics_appopen_v2.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/analytics_appopen_v2.py", line 9, in <module>
    from default_args import default_args
ModuleNotFoundError: No module named 'default_args'
[2023-02-26 13:20:15,098] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/analytics_appopen_v2.py
[2023-02-26 13:20:15,112] {processor.py:161} INFO - Processing /opt/airflow/dags/analytics_appopen_v2.py took 0.037 seconds
[2023-02-26 13:20:45,289] {processor.py:153} INFO - Started process (PID=2269) to work on /opt/airflow/dags/analytics_appopen_v2.py
[2023-02-26 13:20:45,290] {processor.py:641} INFO - Processing file /opt/airflow/dags/analytics_appopen_v2.py for tasks to queue
[2023-02-26 13:20:45,291] {logging_mixin.py:115} INFO - [2023-02-26 13:20:45,291] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/analytics_appopen_v2.py
[2023-02-26 13:20:45,311] {logging_mixin.py:115} INFO - [2023-02-26 13:20:45,308] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/analytics_appopen_v2.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/analytics_appopen_v2.py", line 9, in <module>
    from default_args import default_args
ModuleNotFoundError: No module named 'default_args'
[2023-02-26 13:20:45,312] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/analytics_appopen_v2.py
[2023-02-26 13:20:45,326] {processor.py:161} INFO - Processing /opt/airflow/dags/analytics_appopen_v2.py took 0.039 seconds
[2023-02-26 13:21:15,489] {processor.py:153} INFO - Started process (PID=2299) to work on /opt/airflow/dags/analytics_appopen_v2.py
[2023-02-26 13:21:15,490] {processor.py:641} INFO - Processing file /opt/airflow/dags/analytics_appopen_v2.py for tasks to queue
[2023-02-26 13:21:15,491] {logging_mixin.py:115} INFO - [2023-02-26 13:21:15,490] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/analytics_appopen_v2.py
[2023-02-26 13:21:15,508] {logging_mixin.py:115} INFO - [2023-02-26 13:21:15,506] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/analytics_appopen_v2.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/analytics_appopen_v2.py", line 9, in <module>
    from default_args import default_args
ModuleNotFoundError: No module named 'default_args'
[2023-02-26 13:21:15,509] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/analytics_appopen_v2.py
[2023-02-26 13:21:15,525] {processor.py:161} INFO - Processing /opt/airflow/dags/analytics_appopen_v2.py took 0.038 seconds
[2023-02-26 13:21:45,791] {processor.py:153} INFO - Started process (PID=2329) to work on /opt/airflow/dags/analytics_appopen_v2.py
[2023-02-26 13:21:45,792] {processor.py:641} INFO - Processing file /opt/airflow/dags/analytics_appopen_v2.py for tasks to queue
[2023-02-26 13:21:45,794] {logging_mixin.py:115} INFO - [2023-02-26 13:21:45,793] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/analytics_appopen_v2.py
[2023-02-26 13:21:45,820] {logging_mixin.py:115} INFO - [2023-02-26 13:21:45,818] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/analytics_appopen_v2.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/analytics_appopen_v2.py", line 9, in <module>
    from default_args import default_args
ModuleNotFoundError: No module named 'default_args'
[2023-02-26 13:21:45,821] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/analytics_appopen_v2.py
[2023-02-26 13:21:45,838] {processor.py:161} INFO - Processing /opt/airflow/dags/analytics_appopen_v2.py took 0.053 seconds
[2023-02-26 13:22:16,000] {processor.py:153} INFO - Started process (PID=2350) to work on /opt/airflow/dags/analytics_appopen_v2.py
[2023-02-26 13:22:16,000] {processor.py:641} INFO - Processing file /opt/airflow/dags/analytics_appopen_v2.py for tasks to queue
[2023-02-26 13:22:16,001] {logging_mixin.py:115} INFO - [2023-02-26 13:22:16,001] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/analytics_appopen_v2.py
[2023-02-26 13:22:16,018] {logging_mixin.py:115} INFO - [2023-02-26 13:22:16,016] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/analytics_appopen_v2.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/analytics_appopen_v2.py", line 9, in <module>
    from default_args import default_args
ModuleNotFoundError: No module named 'default_args'
[2023-02-26 13:22:16,019] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/analytics_appopen_v2.py
[2023-02-26 13:22:16,033] {processor.py:161} INFO - Processing /opt/airflow/dags/analytics_appopen_v2.py took 0.036 seconds
[2023-02-26 13:22:46,197] {processor.py:153} INFO - Started process (PID=2380) to work on /opt/airflow/dags/analytics_appopen_v2.py
[2023-02-26 13:22:46,197] {processor.py:641} INFO - Processing file /opt/airflow/dags/analytics_appopen_v2.py for tasks to queue
[2023-02-26 13:22:46,198] {logging_mixin.py:115} INFO - [2023-02-26 13:22:46,198] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/analytics_appopen_v2.py
[2023-02-26 13:22:46,218] {logging_mixin.py:115} INFO - [2023-02-26 13:22:46,215] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/analytics_appopen_v2.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/analytics_appopen_v2.py", line 9, in <module>
    from default_args import default_args
ModuleNotFoundError: No module named 'default_args'
[2023-02-26 13:22:46,218] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/analytics_appopen_v2.py
[2023-02-26 13:22:46,234] {processor.py:161} INFO - Processing /opt/airflow/dags/analytics_appopen_v2.py took 0.039 seconds
[2023-02-26 13:23:16,418] {processor.py:153} INFO - Started process (PID=2410) to work on /opt/airflow/dags/analytics_appopen_v2.py
[2023-02-26 13:23:16,419] {processor.py:641} INFO - Processing file /opt/airflow/dags/analytics_appopen_v2.py for tasks to queue
[2023-02-26 13:23:16,420] {logging_mixin.py:115} INFO - [2023-02-26 13:23:16,420] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/analytics_appopen_v2.py
[2023-02-26 13:23:16,437] {logging_mixin.py:115} INFO - [2023-02-26 13:23:16,434] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/analytics_appopen_v2.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/analytics_appopen_v2.py", line 9, in <module>
    from default_args import default_args
ModuleNotFoundError: No module named 'default_args'
[2023-02-26 13:23:16,438] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/analytics_appopen_v2.py
[2023-02-26 13:23:16,454] {processor.py:161} INFO - Processing /opt/airflow/dags/analytics_appopen_v2.py took 0.038 seconds
[2023-02-26 13:23:46,602] {processor.py:153} INFO - Started process (PID=2440) to work on /opt/airflow/dags/analytics_appopen_v2.py
[2023-02-26 13:23:46,603] {processor.py:641} INFO - Processing file /opt/airflow/dags/analytics_appopen_v2.py for tasks to queue
[2023-02-26 13:23:46,603] {logging_mixin.py:115} INFO - [2023-02-26 13:23:46,603] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/analytics_appopen_v2.py
[2023-02-26 13:23:46,621] {logging_mixin.py:115} INFO - [2023-02-26 13:23:46,619] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/analytics_appopen_v2.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/analytics_appopen_v2.py", line 9, in <module>
    from default_args import default_args
ModuleNotFoundError: No module named 'default_args'
[2023-02-26 13:23:46,622] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/analytics_appopen_v2.py
[2023-02-26 13:23:46,637] {processor.py:161} INFO - Processing /opt/airflow/dags/analytics_appopen_v2.py took 0.038 seconds
[2023-02-26 13:24:16,803] {processor.py:153} INFO - Started process (PID=2461) to work on /opt/airflow/dags/analytics_appopen_v2.py
[2023-02-26 13:24:16,804] {processor.py:641} INFO - Processing file /opt/airflow/dags/analytics_appopen_v2.py for tasks to queue
[2023-02-26 13:24:16,804] {logging_mixin.py:115} INFO - [2023-02-26 13:24:16,804] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/analytics_appopen_v2.py
[2023-02-26 13:24:16,821] {logging_mixin.py:115} INFO - [2023-02-26 13:24:16,819] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/analytics_appopen_v2.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/analytics_appopen_v2.py", line 9, in <module>
    from default_args import default_args
ModuleNotFoundError: No module named 'default_args'
[2023-02-26 13:24:16,822] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/analytics_appopen_v2.py
[2023-02-26 13:24:16,836] {processor.py:161} INFO - Processing /opt/airflow/dags/analytics_appopen_v2.py took 0.035 seconds
[2023-02-26 13:24:47,008] {processor.py:153} INFO - Started process (PID=2491) to work on /opt/airflow/dags/analytics_appopen_v2.py
[2023-02-26 13:24:47,009] {processor.py:641} INFO - Processing file /opt/airflow/dags/analytics_appopen_v2.py for tasks to queue
[2023-02-26 13:24:47,009] {logging_mixin.py:115} INFO - [2023-02-26 13:24:47,009] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/analytics_appopen_v2.py
[2023-02-26 13:24:47,029] {logging_mixin.py:115} INFO - [2023-02-26 13:24:47,026] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/analytics_appopen_v2.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/analytics_appopen_v2.py", line 9, in <module>
    from default_args import default_args
ModuleNotFoundError: No module named 'default_args'
[2023-02-26 13:24:47,030] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/analytics_appopen_v2.py
[2023-02-26 13:24:47,044] {processor.py:161} INFO - Processing /opt/airflow/dags/analytics_appopen_v2.py took 0.039 seconds
[2023-02-26 13:25:17,208] {processor.py:153} INFO - Started process (PID=2521) to work on /opt/airflow/dags/analytics_appopen_v2.py
[2023-02-26 13:25:17,209] {processor.py:641} INFO - Processing file /opt/airflow/dags/analytics_appopen_v2.py for tasks to queue
[2023-02-26 13:25:17,210] {logging_mixin.py:115} INFO - [2023-02-26 13:25:17,209] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/analytics_appopen_v2.py
[2023-02-26 13:25:17,232] {logging_mixin.py:115} INFO - [2023-02-26 13:25:17,229] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/analytics_appopen_v2.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/analytics_appopen_v2.py", line 9, in <module>
    from default_args import default_args
ModuleNotFoundError: No module named 'default_args'
[2023-02-26 13:25:17,233] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/analytics_appopen_v2.py
[2023-02-26 13:25:17,250] {processor.py:161} INFO - Processing /opt/airflow/dags/analytics_appopen_v2.py took 0.044 seconds
[2023-02-26 13:25:47,404] {processor.py:153} INFO - Started process (PID=2551) to work on /opt/airflow/dags/analytics_appopen_v2.py
[2023-02-26 13:25:47,405] {processor.py:641} INFO - Processing file /opt/airflow/dags/analytics_appopen_v2.py for tasks to queue
[2023-02-26 13:25:47,405] {logging_mixin.py:115} INFO - [2023-02-26 13:25:47,405] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/analytics_appopen_v2.py
[2023-02-26 13:25:47,423] {logging_mixin.py:115} INFO - [2023-02-26 13:25:47,421] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/analytics_appopen_v2.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/analytics_appopen_v2.py", line 9, in <module>
    from default_args import default_args
ModuleNotFoundError: No module named 'default_args'
[2023-02-26 13:25:47,424] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/analytics_appopen_v2.py
[2023-02-26 13:25:47,438] {processor.py:161} INFO - Processing /opt/airflow/dags/analytics_appopen_v2.py took 0.037 seconds
[2023-02-26 13:26:17,578] {processor.py:153} INFO - Started process (PID=2572) to work on /opt/airflow/dags/analytics_appopen_v2.py
[2023-02-26 13:26:17,578] {processor.py:641} INFO - Processing file /opt/airflow/dags/analytics_appopen_v2.py for tasks to queue
[2023-02-26 13:26:17,579] {logging_mixin.py:115} INFO - [2023-02-26 13:26:17,579] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/analytics_appopen_v2.py
[2023-02-26 13:26:17,605] {logging_mixin.py:115} INFO - [2023-02-26 13:26:17,603] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/analytics_appopen_v2.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/analytics_appopen_v2.py", line 9, in <module>
    from default_args import default_args
ModuleNotFoundError: No module named 'default_args'
[2023-02-26 13:26:17,607] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/analytics_appopen_v2.py
[2023-02-26 13:26:17,636] {processor.py:161} INFO - Processing /opt/airflow/dags/analytics_appopen_v2.py took 0.061 seconds
[2023-02-26 13:26:47,817] {processor.py:153} INFO - Started process (PID=2602) to work on /opt/airflow/dags/analytics_appopen_v2.py
[2023-02-26 13:26:47,817] {processor.py:641} INFO - Processing file /opt/airflow/dags/analytics_appopen_v2.py for tasks to queue
[2023-02-26 13:26:47,818] {logging_mixin.py:115} INFO - [2023-02-26 13:26:47,818] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/analytics_appopen_v2.py
[2023-02-26 13:26:47,835] {logging_mixin.py:115} INFO - [2023-02-26 13:26:47,833] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/analytics_appopen_v2.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/analytics_appopen_v2.py", line 9, in <module>
    from default_args import default_args
ModuleNotFoundError: No module named 'default_args'
[2023-02-26 13:26:47,836] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/analytics_appopen_v2.py
[2023-02-26 13:26:47,850] {processor.py:161} INFO - Processing /opt/airflow/dags/analytics_appopen_v2.py took 0.036 seconds
[2023-02-26 13:27:18,006] {processor.py:153} INFO - Started process (PID=2632) to work on /opt/airflow/dags/analytics_appopen_v2.py
[2023-02-26 13:27:18,006] {processor.py:641} INFO - Processing file /opt/airflow/dags/analytics_appopen_v2.py for tasks to queue
[2023-02-26 13:27:18,007] {logging_mixin.py:115} INFO - [2023-02-26 13:27:18,007] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/analytics_appopen_v2.py
[2023-02-26 13:27:18,026] {logging_mixin.py:115} INFO - [2023-02-26 13:27:18,024] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/analytics_appopen_v2.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/analytics_appopen_v2.py", line 9, in <module>
    from default_args import default_args
ModuleNotFoundError: No module named 'default_args'
[2023-02-26 13:27:18,027] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/analytics_appopen_v2.py
[2023-02-26 13:27:18,044] {processor.py:161} INFO - Processing /opt/airflow/dags/analytics_appopen_v2.py took 0.041 seconds
[2023-02-26 13:27:48,185] {processor.py:153} INFO - Started process (PID=2661) to work on /opt/airflow/dags/analytics_appopen_v2.py
[2023-02-26 13:27:48,186] {processor.py:641} INFO - Processing file /opt/airflow/dags/analytics_appopen_v2.py for tasks to queue
[2023-02-26 13:27:48,188] {logging_mixin.py:115} INFO - [2023-02-26 13:27:48,187] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/analytics_appopen_v2.py
[2023-02-26 13:27:48,222] {logging_mixin.py:115} INFO - [2023-02-26 13:27:48,218] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/analytics_appopen_v2.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/analytics_appopen_v2.py", line 9, in <module>
    from default_args import default_args
ModuleNotFoundError: No module named 'default_args'
[2023-02-26 13:27:48,223] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/analytics_appopen_v2.py
[2023-02-26 13:27:48,241] {processor.py:161} INFO - Processing /opt/airflow/dags/analytics_appopen_v2.py took 0.061 seconds
[2023-02-26 13:28:18,410] {processor.py:153} INFO - Started process (PID=2681) to work on /opt/airflow/dags/analytics_appopen_v2.py
[2023-02-26 13:28:18,410] {processor.py:641} INFO - Processing file /opt/airflow/dags/analytics_appopen_v2.py for tasks to queue
[2023-02-26 13:28:18,411] {logging_mixin.py:115} INFO - [2023-02-26 13:28:18,411] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/analytics_appopen_v2.py
[2023-02-26 13:28:18,434] {logging_mixin.py:115} INFO - [2023-02-26 13:28:18,431] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/analytics_appopen_v2.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/analytics_appopen_v2.py", line 9, in <module>
    from default_args import default_args
ModuleNotFoundError: No module named 'default_args'
[2023-02-26 13:28:18,436] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/analytics_appopen_v2.py
[2023-02-26 13:28:18,463] {processor.py:161} INFO - Processing /opt/airflow/dags/analytics_appopen_v2.py took 0.057 seconds
[2023-02-26 13:28:48,656] {processor.py:153} INFO - Started process (PID=2711) to work on /opt/airflow/dags/analytics_appopen_v2.py
[2023-02-26 13:28:48,656] {processor.py:641} INFO - Processing file /opt/airflow/dags/analytics_appopen_v2.py for tasks to queue
[2023-02-26 13:28:48,657] {logging_mixin.py:115} INFO - [2023-02-26 13:28:48,657] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/analytics_appopen_v2.py
[2023-02-26 13:28:48,675] {logging_mixin.py:115} INFO - [2023-02-26 13:28:48,673] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/analytics_appopen_v2.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/analytics_appopen_v2.py", line 9, in <module>
    from default_args import default_args
ModuleNotFoundError: No module named 'default_args'
[2023-02-26 13:28:48,675] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/analytics_appopen_v2.py
[2023-02-26 13:28:48,690] {processor.py:161} INFO - Processing /opt/airflow/dags/analytics_appopen_v2.py took 0.038 seconds
[2023-02-26 13:29:18,897] {processor.py:153} INFO - Started process (PID=2741) to work on /opt/airflow/dags/analytics_appopen_v2.py
[2023-02-26 13:29:18,898] {processor.py:641} INFO - Processing file /opt/airflow/dags/analytics_appopen_v2.py for tasks to queue
[2023-02-26 13:29:18,899] {logging_mixin.py:115} INFO - [2023-02-26 13:29:18,899] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/analytics_appopen_v2.py
[2023-02-26 13:29:18,917] {logging_mixin.py:115} INFO - [2023-02-26 13:29:18,915] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/analytics_appopen_v2.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/analytics_appopen_v2.py", line 9, in <module>
    from default_args import default_args
ModuleNotFoundError: No module named 'default_args'
[2023-02-26 13:29:18,918] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/analytics_appopen_v2.py
[2023-02-26 13:29:18,933] {processor.py:161} INFO - Processing /opt/airflow/dags/analytics_appopen_v2.py took 0.039 seconds
[2023-02-26 13:29:49,117] {processor.py:153} INFO - Started process (PID=2762) to work on /opt/airflow/dags/analytics_appopen_v2.py
[2023-02-26 13:29:49,118] {processor.py:641} INFO - Processing file /opt/airflow/dags/analytics_appopen_v2.py for tasks to queue
[2023-02-26 13:29:49,119] {logging_mixin.py:115} INFO - [2023-02-26 13:29:49,119] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/analytics_appopen_v2.py
[2023-02-26 13:29:49,137] {logging_mixin.py:115} INFO - [2023-02-26 13:29:49,135] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/analytics_appopen_v2.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/analytics_appopen_v2.py", line 9, in <module>
    from default_args import default_args
ModuleNotFoundError: No module named 'default_args'
[2023-02-26 13:29:49,138] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/analytics_appopen_v2.py
[2023-02-26 13:29:49,154] {processor.py:161} INFO - Processing /opt/airflow/dags/analytics_appopen_v2.py took 0.040 seconds
[2023-02-26 13:30:19,340] {processor.py:153} INFO - Started process (PID=2792) to work on /opt/airflow/dags/analytics_appopen_v2.py
[2023-02-26 13:30:19,340] {processor.py:641} INFO - Processing file /opt/airflow/dags/analytics_appopen_v2.py for tasks to queue
[2023-02-26 13:30:19,341] {logging_mixin.py:115} INFO - [2023-02-26 13:30:19,341] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/analytics_appopen_v2.py
[2023-02-26 13:30:19,359] {logging_mixin.py:115} INFO - [2023-02-26 13:30:19,357] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/analytics_appopen_v2.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/analytics_appopen_v2.py", line 9, in <module>
    from default_args import default_args
ModuleNotFoundError: No module named 'default_args'
[2023-02-26 13:30:19,360] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/analytics_appopen_v2.py
[2023-02-26 13:30:19,399] {processor.py:161} INFO - Processing /opt/airflow/dags/analytics_appopen_v2.py took 0.062 seconds
[2023-02-26 13:30:49,828] {processor.py:153} INFO - Started process (PID=2822) to work on /opt/airflow/dags/analytics_appopen_v2.py
[2023-02-26 13:30:49,829] {processor.py:641} INFO - Processing file /opt/airflow/dags/analytics_appopen_v2.py for tasks to queue
[2023-02-26 13:30:49,830] {logging_mixin.py:115} INFO - [2023-02-26 13:30:49,829] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/analytics_appopen_v2.py
[2023-02-26 13:30:49,845] {logging_mixin.py:115} INFO - [2023-02-26 13:30:49,843] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/analytics_appopen_v2.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/analytics_appopen_v2.py", line 9, in <module>
    from default_args import default_args
ModuleNotFoundError: No module named 'default_args'
[2023-02-26 13:30:49,846] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/analytics_appopen_v2.py
[2023-02-26 13:30:49,860] {processor.py:161} INFO - Processing /opt/airflow/dags/analytics_appopen_v2.py took 0.034 seconds
[2023-02-26 13:31:20,039] {processor.py:153} INFO - Started process (PID=2852) to work on /opt/airflow/dags/analytics_appopen_v2.py
[2023-02-26 13:31:20,039] {processor.py:641} INFO - Processing file /opt/airflow/dags/analytics_appopen_v2.py for tasks to queue
[2023-02-26 13:31:20,040] {logging_mixin.py:115} INFO - [2023-02-26 13:31:20,040] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/analytics_appopen_v2.py
[2023-02-26 13:31:20,059] {logging_mixin.py:115} INFO - [2023-02-26 13:31:20,057] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/analytics_appopen_v2.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/analytics_appopen_v2.py", line 9, in <module>
    from default_args import default_args
ModuleNotFoundError: No module named 'default_args'
[2023-02-26 13:31:20,061] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/analytics_appopen_v2.py
[2023-02-26 13:31:20,079] {processor.py:161} INFO - Processing /opt/airflow/dags/analytics_appopen_v2.py took 0.043 seconds
[2023-02-26 13:31:50,357] {processor.py:153} INFO - Started process (PID=2873) to work on /opt/airflow/dags/analytics_appopen_v2.py
[2023-02-26 13:31:50,358] {processor.py:641} INFO - Processing file /opt/airflow/dags/analytics_appopen_v2.py for tasks to queue
[2023-02-26 13:31:50,358] {logging_mixin.py:115} INFO - [2023-02-26 13:31:50,358] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/analytics_appopen_v2.py
[2023-02-26 13:31:50,376] {logging_mixin.py:115} INFO - [2023-02-26 13:31:50,374] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/analytics_appopen_v2.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/analytics_appopen_v2.py", line 9, in <module>
    from default_args import default_args
ModuleNotFoundError: No module named 'default_args'
[2023-02-26 13:31:50,377] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/analytics_appopen_v2.py
[2023-02-26 13:31:50,392] {processor.py:161} INFO - Processing /opt/airflow/dags/analytics_appopen_v2.py took 0.037 seconds
[2023-02-26 13:32:20,578] {processor.py:153} INFO - Started process (PID=2903) to work on /opt/airflow/dags/analytics_appopen_v2.py
[2023-02-26 13:32:20,578] {processor.py:641} INFO - Processing file /opt/airflow/dags/analytics_appopen_v2.py for tasks to queue
[2023-02-26 13:32:20,579] {logging_mixin.py:115} INFO - [2023-02-26 13:32:20,579] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/analytics_appopen_v2.py
[2023-02-26 13:32:20,596] {logging_mixin.py:115} INFO - [2023-02-26 13:32:20,593] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/analytics_appopen_v2.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/analytics_appopen_v2.py", line 9, in <module>
    from default_args import default_args
ModuleNotFoundError: No module named 'default_args'
[2023-02-26 13:32:20,596] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/analytics_appopen_v2.py
[2023-02-26 13:32:20,611] {processor.py:161} INFO - Processing /opt/airflow/dags/analytics_appopen_v2.py took 0.035 seconds
[2023-02-26 13:32:50,789] {processor.py:153} INFO - Started process (PID=2933) to work on /opt/airflow/dags/analytics_appopen_v2.py
[2023-02-26 13:32:50,790] {processor.py:641} INFO - Processing file /opt/airflow/dags/analytics_appopen_v2.py for tasks to queue
[2023-02-26 13:32:50,790] {logging_mixin.py:115} INFO - [2023-02-26 13:32:50,790] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/analytics_appopen_v2.py
[2023-02-26 13:32:50,812] {logging_mixin.py:115} INFO - [2023-02-26 13:32:50,809] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/analytics_appopen_v2.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/analytics_appopen_v2.py", line 9, in <module>
    from default_args import default_args
ModuleNotFoundError: No module named 'default_args'
[2023-02-26 13:32:50,813] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/analytics_appopen_v2.py
[2023-02-26 13:32:50,831] {processor.py:161} INFO - Processing /opt/airflow/dags/analytics_appopen_v2.py took 0.045 seconds
[2023-02-26 13:33:21,020] {processor.py:153} INFO - Started process (PID=2963) to work on /opt/airflow/dags/analytics_appopen_v2.py
[2023-02-26 13:33:21,021] {processor.py:641} INFO - Processing file /opt/airflow/dags/analytics_appopen_v2.py for tasks to queue
[2023-02-26 13:33:21,022] {logging_mixin.py:115} INFO - [2023-02-26 13:33:21,022] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/analytics_appopen_v2.py
[2023-02-26 13:33:21,043] {logging_mixin.py:115} INFO - [2023-02-26 13:33:21,042] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/analytics_appopen_v2.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/analytics_appopen_v2.py", line 9, in <module>
    from default_args import default_args
ModuleNotFoundError: No module named 'default_args'
[2023-02-26 13:33:21,045] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/analytics_appopen_v2.py
[2023-02-26 13:33:21,061] {processor.py:161} INFO - Processing /opt/airflow/dags/analytics_appopen_v2.py took 0.045 seconds
[2023-02-26 13:33:51,244] {processor.py:153} INFO - Started process (PID=2984) to work on /opt/airflow/dags/analytics_appopen_v2.py
[2023-02-26 13:33:51,244] {processor.py:641} INFO - Processing file /opt/airflow/dags/analytics_appopen_v2.py for tasks to queue
[2023-02-26 13:33:51,245] {logging_mixin.py:115} INFO - [2023-02-26 13:33:51,245] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/analytics_appopen_v2.py
[2023-02-26 13:33:51,263] {logging_mixin.py:115} INFO - [2023-02-26 13:33:51,260] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/analytics_appopen_v2.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/analytics_appopen_v2.py", line 9, in <module>
    from default_args import default_args
ModuleNotFoundError: No module named 'default_args'
[2023-02-26 13:33:51,263] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/analytics_appopen_v2.py
[2023-02-26 13:33:51,278] {processor.py:161} INFO - Processing /opt/airflow/dags/analytics_appopen_v2.py took 0.037 seconds
[2023-02-26 13:33:59,298] {processor.py:153} INFO - Started process (PID=2994) to work on /opt/airflow/dags/analytics_appopen_v2.py
[2023-02-26 13:33:59,298] {processor.py:641} INFO - Processing file /opt/airflow/dags/analytics_appopen_v2.py for tasks to queue
[2023-02-26 13:33:59,299] {logging_mixin.py:115} INFO - [2023-02-26 13:33:59,299] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/analytics_appopen_v2.py
[2023-02-26 13:33:59,330] {logging_mixin.py:115} INFO - [2023-02-26 13:33:59,328] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/analytics_appopen_v2.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/analytics_appopen_v2.py", line 9, in <module>
    from default_args import default_args
ModuleNotFoundError: No module named 'default_args'
[2023-02-26 13:33:59,331] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/analytics_appopen_v2.py
[2023-02-26 13:33:59,345] {processor.py:161} INFO - Processing /opt/airflow/dags/analytics_appopen_v2.py took 0.050 seconds
[2023-02-26 13:34:29,528] {processor.py:153} INFO - Started process (PID=3024) to work on /opt/airflow/dags/analytics_appopen_v2.py
[2023-02-26 13:34:29,528] {processor.py:641} INFO - Processing file /opt/airflow/dags/analytics_appopen_v2.py for tasks to queue
[2023-02-26 13:34:29,529] {logging_mixin.py:115} INFO - [2023-02-26 13:34:29,529] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/analytics_appopen_v2.py
[2023-02-26 13:34:29,546] {logging_mixin.py:115} INFO - [2023-02-26 13:34:29,544] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/analytics_appopen_v2.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/analytics_appopen_v2.py", line 9, in <module>
    from default_args import default_args
ModuleNotFoundError: No module named 'default_args'
[2023-02-26 13:34:29,547] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/analytics_appopen_v2.py
[2023-02-26 13:34:29,562] {processor.py:161} INFO - Processing /opt/airflow/dags/analytics_appopen_v2.py took 0.037 seconds
[2023-02-26 13:34:36,618] {processor.py:153} INFO - Started process (PID=3036) to work on /opt/airflow/dags/analytics_appopen_v2.py
[2023-02-26 13:34:36,619] {processor.py:641} INFO - Processing file /opt/airflow/dags/analytics_appopen_v2.py for tasks to queue
[2023-02-26 13:34:36,619] {logging_mixin.py:115} INFO - [2023-02-26 13:34:36,619] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/analytics_appopen_v2.py
[2023-02-26 13:34:36,652] {logging_mixin.py:115} INFO - [2023-02-26 13:34:36,650] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/analytics_appopen_v2.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/analytics_appopen_v2.py", line 9, in <module>
    from default_args import default_args
ModuleNotFoundError: No module named 'default_args'
[2023-02-26 13:34:36,653] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/analytics_appopen_v2.py
[2023-02-26 13:34:36,670] {processor.py:161} INFO - Processing /opt/airflow/dags/analytics_appopen_v2.py took 0.054 seconds
[2023-02-26 13:34:56,741] {processor.py:153} INFO - Started process (PID=3046) to work on /opt/airflow/dags/analytics_appopen_v2.py
[2023-02-26 13:34:56,741] {processor.py:641} INFO - Processing file /opt/airflow/dags/analytics_appopen_v2.py for tasks to queue
[2023-02-26 13:34:56,742] {logging_mixin.py:115} INFO - [2023-02-26 13:34:56,742] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/analytics_appopen_v2.py
[2023-02-26 13:34:56,778] {logging_mixin.py:115} INFO - [2023-02-26 13:34:56,776] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/analytics_appopen_v2.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/analytics_appopen_v2.py", line 9, in <module>
    from default_args import default_args
ModuleNotFoundError: No module named 'default_args'
[2023-02-26 13:34:56,779] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/analytics_appopen_v2.py
[2023-02-26 13:34:56,794] {processor.py:161} INFO - Processing /opt/airflow/dags/analytics_appopen_v2.py took 0.057 seconds
[2023-02-26 13:34:59,788] {processor.py:153} INFO - Started process (PID=3056) to work on /opt/airflow/dags/analytics_appopen_v2.py
[2023-02-26 13:34:59,789] {processor.py:641} INFO - Processing file /opt/airflow/dags/analytics_appopen_v2.py for tasks to queue
[2023-02-26 13:34:59,789] {logging_mixin.py:115} INFO - [2023-02-26 13:34:59,789] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/analytics_appopen_v2.py
[2023-02-26 13:34:59,822] {logging_mixin.py:115} INFO - [2023-02-26 13:34:59,820] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/analytics_appopen_v2.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/analytics_appopen_v2.py", line 9, in <module>
    from default_args import default_args
ModuleNotFoundError: No module named 'default_args'
[2023-02-26 13:34:59,823] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/analytics_appopen_v2.py
[2023-02-26 13:34:59,837] {processor.py:161} INFO - Processing /opt/airflow/dags/analytics_appopen_v2.py took 0.051 seconds
[2023-02-26 13:35:30,002] {processor.py:153} INFO - Started process (PID=3077) to work on /opt/airflow/dags/analytics_appopen_v2.py
[2023-02-26 13:35:30,003] {processor.py:641} INFO - Processing file /opt/airflow/dags/analytics_appopen_v2.py for tasks to queue
[2023-02-26 13:35:30,004] {logging_mixin.py:115} INFO - [2023-02-26 13:35:30,004] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/analytics_appopen_v2.py
[2023-02-26 13:35:30,024] {logging_mixin.py:115} INFO - [2023-02-26 13:35:30,022] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/analytics_appopen_v2.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/analytics_appopen_v2.py", line 9, in <module>
    from default_args import default_args
ModuleNotFoundError: No module named 'default_args'
[2023-02-26 13:35:30,025] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/analytics_appopen_v2.py
[2023-02-26 13:35:30,041] {processor.py:161} INFO - Processing /opt/airflow/dags/analytics_appopen_v2.py took 0.042 seconds
[2023-02-26 13:35:34,022] {processor.py:153} INFO - Started process (PID=3087) to work on /opt/airflow/dags/analytics_appopen_v2.py
[2023-02-26 13:35:34,023] {processor.py:641} INFO - Processing file /opt/airflow/dags/analytics_appopen_v2.py for tasks to queue
[2023-02-26 13:35:34,023] {logging_mixin.py:115} INFO - [2023-02-26 13:35:34,023] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/analytics_appopen_v2.py
[2023-02-26 13:35:34,113] {logging_mixin.py:115} INFO - [2023-02-26 13:35:34,109] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/analytics_appopen_v2.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/analytics_appopen_v2.py", line 9, in <module>
    from default_args import default_args
ModuleNotFoundError: No module named 'default_args'
[2023-02-26 13:35:34,114] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/analytics_appopen_v2.py
[2023-02-26 13:35:34,132] {processor.py:161} INFO - Processing /opt/airflow/dags/analytics_appopen_v2.py took 0.113 seconds
