[2023-02-26 14:47:59,863] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: get_taxi_availability.taxi_api_to_db manual__2023-02-26T14:47:57.505866+00:00 [queued]>
[2023-02-26 14:47:59,872] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: get_taxi_availability.taxi_api_to_db manual__2023-02-26T14:47:57.505866+00:00 [queued]>
[2023-02-26 14:47:59,873] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2023-02-26 14:47:59,873] {taskinstance.py:1357} INFO - Starting attempt 1 of 3
[2023-02-26 14:47:59,873] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2023-02-26 14:47:59,883] {taskinstance.py:1377} INFO - Executing <Task(PythonOperator): taxi_api_to_db> on 2023-02-26 14:47:57.505866+00:00
[2023-02-26 14:47:59,888] {standard_task_runner.py:52} INFO - Started process 6492 to run task
[2023-02-26 14:47:59,891] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'get_taxi_availability', 'taxi_api_to_db', 'manual__2023-02-26T14:47:57.505866+00:00', '--job-id', '20', '--raw', '--subdir', 'DAGS_FOLDER/get_taxi_availability.py', '--cfg-path', '/tmp/tmpss2z9rmq', '--error-file', '/tmp/tmp5f91ql00']
[2023-02-26 14:47:59,891] {standard_task_runner.py:80} INFO - Job 20: Subtask taxi_api_to_db
[2023-02-26 14:47:59,933] {task_command.py:370} INFO - Running <TaskInstance: get_taxi_availability.taxi_api_to_db manual__2023-02-26T14:47:57.505866+00:00 [running]> on host 0337baec7fd8
[2023-02-26 14:47:59,987] {taskinstance.py:1571} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=get_taxi_availability
AIRFLOW_CTX_TASK_ID=taxi_api_to_db
AIRFLOW_CTX_EXECUTION_DATE=2023-02-26T14:47:57.505866+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-02-26T14:47:57.505866+00:00
[2023-02-26 14:47:59,989] {taskinstance.py:1889} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 171, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 189, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/functions/taxi_availability.py", line 93, in run_taxi_api_to_db
    db1.run(query)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/hooks/dbapi.py", line 184, in run
    raise ValueError("List of SQL statements is empty")
ValueError: List of SQL statements is empty
[2023-02-26 14:47:59,998] {taskinstance.py:1400} INFO - Marking task as UP_FOR_RETRY. dag_id=get_taxi_availability, task_id=taxi_api_to_db, execution_date=20230226T144757, start_date=20230226T144759, end_date=20230226T144759
[2023-02-26 14:48:00,006] {standard_task_runner.py:97} ERROR - Failed to execute job 20 for task taxi_api_to_db (List of SQL statements is empty; 6492)
[2023-02-26 14:48:00,024] {local_task_job.py:156} INFO - Task exited with return code 1
[2023-02-26 14:48:00,053] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
