[2023-02-26 15:15:01,689] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: get_taxi_availability.taxi_api_to_db scheduled__2023-02-26T15:12:00+00:00 [queued]>
[2023-02-26 15:15:01,696] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: get_taxi_availability.taxi_api_to_db scheduled__2023-02-26T15:12:00+00:00 [queued]>
[2023-02-26 15:15:01,696] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2023-02-26 15:15:01,696] {taskinstance.py:1357} INFO - Starting attempt 1 of 3
[2023-02-26 15:15:01,697] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2023-02-26 15:15:01,709] {taskinstance.py:1377} INFO - Executing <Task(PythonOperator): taxi_api_to_db> on 2023-02-26 15:12:00+00:00
[2023-02-26 15:15:01,714] {standard_task_runner.py:52} INFO - Started process 7921 to run task
[2023-02-26 15:15:01,716] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'get_taxi_availability', 'taxi_api_to_db', 'scheduled__2023-02-26T15:12:00+00:00', '--job-id', '59', '--raw', '--subdir', 'DAGS_FOLDER/get_taxi_availability.py', '--cfg-path', '/tmp/tmpielywt0p', '--error-file', '/tmp/tmpsss62n_8']
[2023-02-26 15:15:01,717] {standard_task_runner.py:80} INFO - Job 59: Subtask taxi_api_to_db
[2023-02-26 15:15:01,728] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/***/configuration.py:525: DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
  option = self._get_environment_variables(deprecated_key, deprecated_section, key, section)

[2023-02-26 15:15:01,760] {task_command.py:370} INFO - Running <TaskInstance: get_taxi_availability.taxi_api_to_db scheduled__2023-02-26T15:12:00+00:00 [running]> on host 0337baec7fd8
[2023-02-26 15:15:01,817] {taskinstance.py:1571} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=get_taxi_availability
AIRFLOW_CTX_TASK_ID=taxi_api_to_db
AIRFLOW_CTX_EXECUTION_DATE=2023-02-26T15:12:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2023-02-26T15:12:00+00:00
[2023-02-26 15:15:02,274] {logging_mixin.py:115} INFO - Succesful connection with API.
[2023-02-26 15:15:02,275] {logging_mixin.py:115} INFO - -------------------------------
[2023-02-26 15:15:02,280] {taskinstance.py:1889} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 171, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 189, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/functions/taxi_availability.py", line 85, in run_taxi_api_to_db
    etl.transform()
  File "/opt/airflow/dags/functions/taxi_availability.py", line 57, in transform
    df['features']=json.dumps(df['features'])
  File "/usr/local/lib/python3.7/json/__init__.py", line 231, in dumps
    return _default_encoder.encode(obj)
  File "/usr/local/lib/python3.7/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/local/lib/python3.7/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/usr/local/lib/python3.7/json/encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type Series is not JSON serializable
[2023-02-26 15:15:02,292] {taskinstance.py:1400} INFO - Marking task as UP_FOR_RETRY. dag_id=get_taxi_availability, task_id=taxi_api_to_db, execution_date=20230226T151200, start_date=20230226T151501, end_date=20230226T151502
[2023-02-26 15:15:02,304] {standard_task_runner.py:97} ERROR - Failed to execute job 59 for task taxi_api_to_db (Object of type Series is not JSON serializable; 7921)
[2023-02-26 15:15:02,330] {local_task_job.py:156} INFO - Task exited with return code 1
[2023-02-26 15:15:02,364] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
