[2023-02-26 15:09:02,994] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: get_taxi_availability.taxi_api_to_db manual__2023-02-26T15:09:01.799235+00:00 [queued]>
[2023-02-26 15:09:03,004] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: get_taxi_availability.taxi_api_to_db manual__2023-02-26T15:09:01.799235+00:00 [queued]>
[2023-02-26 15:09:03,004] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2023-02-26 15:09:03,005] {taskinstance.py:1357} INFO - Starting attempt 1 of 3
[2023-02-26 15:09:03,005] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2023-02-26 15:09:03,017] {taskinstance.py:1377} INFO - Executing <Task(PythonOperator): taxi_api_to_db> on 2023-02-26 15:09:01.799235+00:00
[2023-02-26 15:09:03,024] {standard_task_runner.py:52} INFO - Started process 7615 to run task
[2023-02-26 15:09:03,034] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'get_taxi_availability', 'taxi_api_to_db', 'manual__2023-02-26T15:09:01.799235+00:00', '--job-id', '53', '--raw', '--subdir', 'DAGS_FOLDER/get_taxi_availability.py', '--cfg-path', '/tmp/tmplyhyj3xf', '--error-file', '/tmp/tmpwn1lzynr']
[2023-02-26 15:09:03,035] {standard_task_runner.py:80} INFO - Job 53: Subtask taxi_api_to_db
[2023-02-26 15:09:03,107] {task_command.py:370} INFO - Running <TaskInstance: get_taxi_availability.taxi_api_to_db manual__2023-02-26T15:09:01.799235+00:00 [running]> on host 0337baec7fd8
[2023-02-26 15:09:03,198] {taskinstance.py:1571} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=get_taxi_availability
AIRFLOW_CTX_TASK_ID=taxi_api_to_db
AIRFLOW_CTX_EXECUTION_DATE=2023-02-26T15:09:01.799235+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-02-26T15:09:01.799235+00:00
[2023-02-26 15:09:04,080] {logging_mixin.py:115} INFO - Succesful connection with API.
[2023-02-26 15:09:04,081] {logging_mixin.py:115} INFO - -------------------------------
[2023-02-26 15:09:04,090] {warnings.py:110} WARNING - /opt/***/dags/functions/taxi_availability.py:51: FutureWarning: The default value of regex will change from True to False in a future version. In addition, single character regular expressions will *not* be treated as literal strings when regex=True.
  df['features'] = df['features'].str.replace("[","'[")

[2023-02-26 15:09:04,092] {taskinstance.py:1889} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 171, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 189, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/functions/taxi_availability.py", line 76, in run_taxi_api_to_db
    etl.transform()
  File "/opt/airflow/dags/functions/taxi_availability.py", line 52, in transform
    df['features'] = df['features'].str.replace("]","]'")
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/core/generic.py", line 5487, in __getattr__
    return object.__getattribute__(self, name)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/core/accessor.py", line 181, in __get__
    accessor_obj = self._accessor(obj)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/core/strings/accessor.py", line 168, in __init__
    self._inferred_dtype = self._validate(data)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/core/strings/accessor.py", line 225, in _validate
    raise AttributeError("Can only use .str accessor with string values!")
AttributeError: Can only use .str accessor with string values!
[2023-02-26 15:09:04,105] {taskinstance.py:1400} INFO - Marking task as UP_FOR_RETRY. dag_id=get_taxi_availability, task_id=taxi_api_to_db, execution_date=20230226T150901, start_date=20230226T150902, end_date=20230226T150904
[2023-02-26 15:09:04,118] {standard_task_runner.py:97} ERROR - Failed to execute job 53 for task taxi_api_to_db (Can only use .str accessor with string values!; 7615)
[2023-02-26 15:09:04,132] {local_task_job.py:156} INFO - Task exited with return code 1
[2023-02-26 15:09:04,175] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
