[2023-02-26 14:49:04,368] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: get_taxi_availability.taxi_api_to_db scheduled__2023-02-26T14:45:00+00:00 [queued]>
[2023-02-26 14:49:04,376] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: get_taxi_availability.taxi_api_to_db scheduled__2023-02-26T14:45:00+00:00 [queued]>
[2023-02-26 14:49:04,377] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2023-02-26 14:49:04,377] {taskinstance.py:1357} INFO - Starting attempt 3 of 3
[2023-02-26 14:49:04,377] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2023-02-26 14:49:04,387] {taskinstance.py:1377} INFO - Executing <Task(PythonOperator): taxi_api_to_db> on 2023-02-26 14:45:00+00:00
[2023-02-26 14:49:04,392] {standard_task_runner.py:52} INFO - Started process 6561 to run task
[2023-02-26 14:49:04,394] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'get_taxi_availability', 'taxi_api_to_db', 'scheduled__2023-02-26T14:45:00+00:00', '--job-id', '25', '--raw', '--subdir', 'DAGS_FOLDER/get_taxi_availability.py', '--cfg-path', '/tmp/tmp01et0coy', '--error-file', '/tmp/tmpbchklyd5']
[2023-02-26 14:49:04,395] {standard_task_runner.py:80} INFO - Job 25: Subtask taxi_api_to_db
[2023-02-26 14:49:04,405] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/***/configuration.py:525: DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
  option = self._get_environment_variables(deprecated_key, deprecated_section, key, section)

[2023-02-26 14:49:04,433] {task_command.py:370} INFO - Running <TaskInstance: get_taxi_availability.taxi_api_to_db scheduled__2023-02-26T14:45:00+00:00 [running]> on host 0337baec7fd8
[2023-02-26 14:49:04,488] {taskinstance.py:1571} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=get_taxi_availability
AIRFLOW_CTX_TASK_ID=taxi_api_to_db
AIRFLOW_CTX_EXECUTION_DATE=2023-02-26T14:45:00+00:00
AIRFLOW_CTX_TRY_NUMBER=3
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2023-02-26T14:45:00+00:00
[2023-02-26 14:49:04,712] {taskinstance.py:1889} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 171, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 189, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/functions/taxi_availability.py", line 93, in run_taxi_api_to_db
    db1.run(query)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/hooks/dbapi.py", line 186, in run
    with closing(self.get_conn()) as conn:
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/postgres/hooks/postgres.py", line 86, in get_conn
    conn = deepcopy(self.connection or self.get_connection(conn_id))
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/hooks/base.py", line 67, in get_connection
    conn = Connection.get_connection_from_secrets(conn_id)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/connection.py", line 430, in get_connection_from_secrets
    raise AirflowNotFoundException(f"The conn_id `{conn_id}` isn't defined")
airflow.exceptions.AirflowNotFoundException: The conn_id `postgres_default` isn't defined
[2023-02-26 14:49:04,720] {taskinstance.py:1400} INFO - Marking task as FAILED. dag_id=get_taxi_availability, task_id=taxi_api_to_db, execution_date=20230226T144500, start_date=20230226T144904, end_date=20230226T144904
[2023-02-26 14:49:04,728] {standard_task_runner.py:97} ERROR - Failed to execute job 25 for task taxi_api_to_db (The conn_id `postgres_default` isn't defined; 6561)
[2023-02-26 14:49:04,768] {local_task_job.py:156} INFO - Task exited with return code 1
[2023-02-26 14:49:04,807] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
